echo "                                                    __ ";
echo " _____     _ _        _ _ _     _                  |  |";
echo "|  |  |___| | |___   | | | |___| |___ ___ _____ ___|  |";
echo "|     | -_| | | . |  | | | | -_| |  _| . |     | -_|__|";
echo "|__|__|___|_|_|___|  |_____|___|_|___|___|_|_|_|___|__|";
echo "                                                       ";

echo "               ,     \    /      ,                ";
echo "              / \    )\__/(     / \               ";        
echo "             /   \  (_\  /_)   /   \              "; 
echo " ___________/_____\__\@  @/___/_____\____________ ";
echo "|                    |\../|                      |";
echo "|                     \VV/                       |";
echo "|    This script will automate the process of    |";
echo "|  installing and configuring programs on a new  |";
echo "|  Linux system (Ubuntu 22.04 and derivatives).  |";
echo "|     https://github.com/j0tz/my_workstation     |";
echo "|              ~ Created by @j0tz ~              |";
echo "|________________________________________________|";
echo " |    /\ /              \\\              \ /\    |";
echo " |  /   V                ))              V   \  | ";
echo " |/     \`               //               ´     \|";
echo " \`                     //                       ´";
echo "                       V                          ";
echo "                                                  ";
